version: 2
updates:
  - package-ecosystem: maven
    directory: "/springboot-client-demo"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10
  - package-ecosystem: maven
    directory: "/springboot-demo"
    schedule:
      interval: daily
      time: '05:00'
      timezone: Asia/Jakarta
    open-pull-requests-limit: 10